def menuimaginarios():
	print("Numeros complejos/imaginarios")
	print("----------------")
	print("1)Suma")
	print("2)Resta")
	print("3)Multiplicación")


menuimaginarios()
opcion=int(input("Ingrese una opción:"))
if opcion==1:
    print("Suma de números imaginarios/complejos")
    print("----------------------------")
    variable1=int(input("Introduce el valor de a:"))
    variable2=int(input("Introduce el valor de b:"))
    variablea=(complex(variable1,variable2))
    print(complex(variable1,variable2))
    variable3=int(input("Introduce el valor de c:"))
    variable4=int(input("Introduce el valor de d:"))
    variableb=(complex(variable3,variable4))
    print(complex(variable3,variable4))
    print("Calculando...")
    print("Resultado de la suma:")
    x = complex(variablea+variableb)
    print(x)
    menuimaginarios()
    opc=int(input("Selecciona una opción:"))
if opcion==2:
	print("Resta de números imaginarios/complejos:")
	print("----------------------")
	variable1=int(input("Introduce el valor de a:"))
	variable2=int(input("Introduce el valor de b:"))
	variablea=(complex(variable1,variable2))
	print(complex(variable1,variable2))
	variable3=int(input("Introduce el valor de c:"))
	variable4=int(input("Introduce el valor de d:"))
	variableb=(complex(variable3,variable4))
	print(complex(variable3,variable4))
	print("Calculando...")
	x=complex(variablea-variableb)
	print(x)
	print("------------------")
	menuimaginarios()
	opc=int(input("Selecciona una opción:"))

if opcion==3:
	print("Multiplicación de números imaginarios/complejos")
	print("-----------------")
	variable1=int(input("Introduce el valor de a:"))
	variable2=int(input("Introduce el valor de b:"))
	print(complex(variable1,variable2))
	variable3=int(input("Introduce el valor de c:"))
	variable4=int(input("Introduce el valor de d:"))
	print(complex(variable3,variable4))
	print("----------------------------")
	print("Calculando...")
	print("...")
	print("Resultado de la multiplicación:")
	x =(variable1*variable3)
	x1=(variable2*variable4)
	y=(variable1*variable4)
	y1=(variable2*variable3)

	print((x-x1)+(y+y1),'j')
	print("-----------------")
	print("::::::::::::::::::::")

	menuimaginarios()
	opc=int(input("Selecciona una opción:"))
